gg.jte.development-mode=true
spring.application.name=webportfolio

# Azure SQL Database Connection Properties
spring.datasource.url=${AZURE_DATABASE_URL}
spring.datasource.username=${AZURE_DATABASE_USERNAME}
spring.datasource.password=${AZURE_DATABASE_PASSWORD}
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect

#telnyx properties
telnyx.api-key=${TELNYX_API_KEY}
telnyx.from-number=${TELNYX_FROM_NUMBER}