gg.jte.development-mode=true
spring.application.name=webportfolio

# Azure SQL Database Connection Properties
spring.datasource.url=jdbc:sqlserver://freddymdb.database.windows.net:1433;database=webappdb;user=server@freddymdb;password={your_password_here};encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
spring.datasource.username=server
spring.datasource.password=Pwd1234.
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect

infobip.api.base-url=https://YOUR_BASE_URL.api.infobip.com
infobip.api.key=YOUR_API_KEY
infobip.api.app-id=YOUR_APP_ID

infobip.sms.sender.number=YOUR_SENDER_NUMBER

